---
name: Lint

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint==1.26.0
          yamllint .
